name = "helloworld"
description = ""
version = "0.1.0-dev"

authors = ["Tali Auster"]
maintainers = ["Tali Auster <me@tali.network>"]
maintainers-logins = ["atalii"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
