name = "withdeps"
description = ""
version = "0.1.0-dev"

authors = ["Tali Auster"]
maintainers = ["Tali Auster <me@tali.network>"]
maintainers-logins = ["atalii"]
licenses = "MPL-2.0"
website = ""
tags = []

[[depends-on]]
simple_logging = "^1.2.0"

[[pins]]
simple_logging = { url='https://github.com/alire-project/simple_logging' }
